# Generated by Django 5.0.6 on 2024-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=300)),
                ('jobdescription', models.CharField(max_length=1000)),
                ('joburl', models.CharField(max_length=200)),
                ('jobbenefit', models.CharField(max_length=1000)),
                ('jobqualification', models.CharField(max_length=1000)),
                ('jobskills', models.CharField(max_length=150)),
                ('joblocation', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=200)),
                ('companyname', models.CharField(max_length=200)),
                ('companydescription', models.CharField(max_length=1000)),
                ('companyimage', models.CharField(max_length=200)),
            ],
        ),
    ]
