# Generated by Django 5.0.6 on 2024-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='companydescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companyimage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companyname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobbenefit',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobdescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='joblocation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobqualification',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobskills',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobtype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='joburl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
