# Generated by Django 5.0.6 on 2024-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_companydescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobpostdate',
            field=models.DateTimeField(null=True),
        ),
    ]
